{'name': 'Simbioz Hr Employee Rotation',
 'version': '14.0.1',
 'category': 'Human Resources/Employees',
 'license': 'LGPL-3',
 'author': "Simbioz Holding",
 'website': 'https://simbioz.ua/',
 'summary': '',
 'depends': ['base',
             'hr_recruitment',
             ],
 'data': ['security/ir.model.access.csv',
          'views/hr_job_employee_rotation.xml',
          ],
 'installable': True,
 'application': False,
 'sequence': 0, }
