# -*- coding: utf-8 -*-

{
    'name': 'RKB Sale Flow',
    'author':   'Yevhen Alieksieiev, Mykyta Maistrenko, Sasha Kochyn',
    'maintainer': 'Simbioz Holding',
    'summary': 'Opportunity -> SO -> PO -> SO, pip3 install tabula-py, pip3 install pdfminer.six',
    'category': 'Sale',
    'website': 'https://www.baspar.ca',
    'version': '11.0.5.11',
    'sequence': 0,
    'external_dependencies': {
                                    "python": ['PyPDF2', 'xlrd', 'tabula', 'pdfminer'],
                                    "bin": [],
                                },
    'excludes': [
                   'rkb_sale_flow',
                   'create_po_from_so',
                   'rkb_email_parser',
                 ],
    'depends': [
                'base',
                'web',
                'crm',
                'product',
                'sale',
                'contacts',
                'sale_crm',
                'sale_margin',
                # 'email_multiple_emails_and_company_alias',
                'sale_order_dates_ext_rkb',
                'sale_commission',
                'purchase',
                'delivery',
                'contract',
                'mail',
                'fleet',
                'analytic',
                'hr_expense',
                'stock',
                'purchase_discount',
                'account_budget',
               ],
    'data': [
            'security/ir.model.access.csv',
            'security/res_groups.xml',
            # 'data/product_item_type_data.xml',
            'data/product_brand_data.xml',
            'data/lead_customer_aim_data.xml',
            'data/zero_product_data.xml',
            'data/mail_template_data.xml',
            'data/ir_sequence_res_partner_data.xml',
            'data/purchase_order_cron.xml',
            # 'data/product_doc_parser_cron.xml',
            'data/product_rkb_category_cron.xml',
            'views/opportunity.xml',
            'views/so.xml',
            'views/analogue_catalogue.xml',
            'views/lead_customer_aim.xml',
            'views/product_item_type.xml',
            'views/product_views.xml',
            'views/purchase_views.xml',
            'views/res_company_view.xml',
            'views/res_partner.xml',
            'views/rkb_customer_activity.xml',
            'views/rkb_department_customer_executive.xml',
            'views/stock_picking_views.xml',
            'views/webclient_templates.xml',
            'views/customer.xml',
            'views/rkb_delivery_condition.xml',
            'views/rkb_delivery_type.xml',
            'views/account_invoice.xml',
            'views/res_config_view.xml',
            'report/invoice_report_templates.xml',
            'report/purchase_order_templates.xml',
            'report/purchase_order_templates.xml',
            'report/purchase_quotation_templates.xml',
            'report/sale_report.xml',
            'wizard/crm_product_order_list_wizard.xml',
            'wizard/sale_order_line_mass_action_wizard.xml',
            'wizard/product_to_crm_lead_wizard.xml',
            # 'data/product.template.csv',
            ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}
