{
    'name': 'DK Purchase Customization',
    'summary': """DK Purchase Customization""",
    'category': 'Purchase Management',
    'author': 'Simbioz',
    'maintainer': 'Simbioz Holding',
    'website': 'https://simbioz.ua',
    'version': '14.0.1.011',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'purchase',
        'account',
        'vendor_pricelist_import',
        'product_secondary_unit',
        'purchase_order_secondary_unit',
        'simbioz_analytic_contract',
    ],
    'images': [],
    'external_dependencies': {
        'python': [],
        'bin': [],
    },
    'data': [
        'views/purchase.xml',
        'views/analytic_account.xml',
        'views/partner.xml',
        'views/product_secondary_unit.xml',
        'views/stock_warehouse.xml',
        'reports/purchase_reports.xml',
        'reports/report_purchase_template.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
